#ifndef SPV_DEFS_HPP_INCLUDE_GUARD
#define SPV_DEFS_HPP_INCLUDE_GUARD

#include <cstdint>

namespace spirv
{
	static constexpr uint32_t magic_number = 0x07230203;
	
	static constexpr uint32_t version_0_99 = 99;
	static constexpr uint32_t version_1_0  = 0x00010000;
	static constexpr uint32_t version_1_1  = 0x00010100;
	static constexpr uint32_t version_1_2  = 0x00010200;
	static constexpr uint32_t version_1_3  = 0x00010300;
	static constexpr uint32_t version_1_4  = 0x00010400;
	static constexpr uint32_t version_1_5  = 0x00010500;
	
	static constexpr uint32_t max_string_chars                    = 0xFFFF;
	static constexpr uint32_t max_id_bound                        = 0x3FFFFF;
	static constexpr uint32_t max_control_flow_nesting            = 0x3FF;
	static constexpr uint32_t max_global_variables                = 0xFFFF;
	static constexpr uint32_t max_local_variables                 = 0x7FFFF;
	static constexpr uint32_t max_execution_modes_per_entry_point = 0xFF;
	static constexpr uint32_t max_access_indices                  = 0xFF;
	static constexpr uint32_t max_function_params                 = 0xFF;
	static constexpr uint32_t max_extinst_params                  = 0xFF;
	static constexpr uint32_t max_switch_labels                   = 0x3FFF;
	static constexpr uint32_t max_structure_nesting               = 0xFF;
	// static constexpr uint32_t max_decorations_per_target       = Number of entries in Decoration
};

enum class SourceLanguage : uint32_t
{
	Unknown        = 0,
	ESSL           = 1,
	GLSL           = 2,
	OpenCL_C       = 3,
	OpenCL_CPP     = 4,
	HLSL           = 5,
	CPP_for_OpenCL = 6,
};

enum class ExecutionModel : uint32_t
{
	Vertex                = 0,
	TesselationControl    = 1,
	TesselationEvaluation = 2,
	Geometry              = 3,
	Fragment              = 4,
	GLCompute             = 5,
	Kernel                = 6,
	TaskNV                = 5267,
	MeshNV                = 5268,
	RayGenerationKHR      = 5313,
	IntersectionKHR       = 5314,
	AnyHitKHR             = 5315,
	ClosestHitKHR         = 5316,
	MissKHR               = 5317,
	CallableKHR           = 5318,
};

enum class AddressingModel : uint32_t
{
	Logical                 = 0,
	Physical32              = 1,
	Physical64              = 2,
	PhysicalStorageBuffer64 = 5348,
};

enum class MemoryModel : uint32_t
{
	Simple  = 0,
	GLSL450 = 1,
	OpenCL  = 2,
	Vulkan  = 3,
};

enum class ExecutionMode : uint32_t
{
	Invocations                      = 0,
	SpacingEqual                     = 1,
	SpacingFractionalEven            = 2,
	SpacingFractionalOdd             = 3,
	VertexOrderCw                    = 4,
	VertexOrderCcw                   = 5,
	PixelCenterInteger               = 6,
	OriginUpperLeft                  = 7,
	OriginLowerLeft                  = 8,
	EarlyFragmentTests               = 9,
	PointMode                        = 10,
	Xfb                              = 11,
	DepthReplacing                   = 12,
	DepthGreater                     = 14,
	DepthLess                        = 15,
	DepthUnchanged                   = 16,
	LocalSize                        = 17,
	LocalSizeHint                    = 18,
	InputPoints                      = 19,
	InputLines                       = 20,
	InputLinesAdjacency              = 21,
	Triangles                        = 22,
	InputTrianglesAdjacency          = 23,
	Quads                            = 24,
	Isolines                         = 25,
	OutputVertices                   = 26,
	OutputPoints                     = 27,
	OutputLineStrip                  = 28,
	OutputTriangleStrip              = 29,
	VecTypeHint                      = 30,
	ContractionOff                   = 31,
	Initializer                      = 33,
	Finalizer                        = 34,
	SubgroupSize                     = 35,
	SubgroupsPerWorkgroup            = 36,
	SubgroupsPerWorkgroupId          = 37,
	LocalSizeId                      = 38,
	LocalSizeHintId                  = 39,
	SubgroupUniformControlFlowKHR    = 4421,
	PostDepthCoverage                = 4446,
	DenormPreserve                   = 4459,
	DenormFlushToZero                = 4460,
	SignedZeroInfNanPreserve         = 4461,
	RoundingModeRTE                  = 4462,
	RoundingModeRTZ                  = 4463,
	StencilRefReplacingEXT           = 5027,
	OutputLinesNV                    = 5269,
	OutputPrimitivesNV               = 5270,
	DerivativeGroupQuadsNV           = 5289,
	DerivativeGroupLinearNV          = 5290,
	OutputTrianglesNV                = 5298,
	PixelInterlockOrderedEXT         = 5366,
	PixelInterlockUnorderedEXT       = 5367,
	SampleInterlockOrderedEXT        = 5368,
	SampleInterlockUnorderedEXT      = 5369,
	ShadingRateInterlockOrderedEXT   = 5370,
	ShadingRateInterlockUnorderedEXT = 5371,
	SharedLocalMemorySizeINTEL       = 5618,
	RoundingModeRTPINTEL             = 5620,
	RoundingModeRTNINTEL             = 5621,
	FloatingPointModeALTINTEL        = 5622,
	FloatingPointModeIEEEINTEL       = 5623,
	MaxWorkgroupSizeINTEL            = 5893,
	MaxWorkDimINTEL                  = 5894,
	NoGlobalOffsetINTEL              = 5895,
	NumSIMDWorkitemsINTEL            = 5896,
	SchedulerTargetFmaxMhzINTEL      = 5903,
};

enum class StorageClass : uint32_t
{
	UniformConstant         = 0,
	Input                   = 1,
	Uniform                 = 2,
	Output                  = 3,
	Workgroup               = 4,
	CrossWorkgroup          = 5,
	Private                 = 6,
	Function                = 7,
	Generic                 = 8,
	PushConstant            = 9,
	AtomicCounter           = 10,
	Image                   = 11,
	StorageBuffer           = 12,
	CallableDataKHR         = 5328,
	IncomingCallableDataKHR = 5329,
	RayPayloadKHR           = 5338,
	HitAttributeKHR         = 5339,
	IncomingRayPayloadKHR   = 5342,
	ShaderRecordBufferKHR   = 5343,
	PhysicalStorageBuffer   = 5349,
	CodeSectionINTEL        = 5605,
	DeviceOnlyINTEL         = 5936,
	HostOnlyINTEL           = 5937,
};

enum class Dim : uint32_t
{
	Dim1D       = 0,
	Dim2D       = 1,
	Dim3D       = 2,
	Cube        = 3,
	Rect        = 4,
	Buffer      = 5,
	SubpassData = 6,
};

enum class SamplerAddressingMode : uint32_t
{
	None           = 0,
	ClampToEdge    = 1,
	Clamp          = 2,
	Repeat         = 3,
	RepeatMirrored = 4,
};

enum class SamplerFilterMode : uint32_t
{
	Nearest = 0,
	Linear  = 1,
};

enum class ImageFormat : uint32_t
{
	Unknown      = 0,
	Rgba32f      = 1,
	Rgba16f      = 2,
	R32f         = 3,
	Rgba8        = 4,
	Rgba8Snorm   = 5,
	Rg32f        = 6,
	Rg16f        = 7,
	R11fG11fB10f = 8,
	R16f         = 9,
	Rgba16       = 10,
	Rgb10A2      = 11,
	Rg16         = 12,
	Rg8          = 13,
	R16          = 14,
	R8           = 15,
	Rgba16Snorm  = 16,
	Rg16Snorm    = 17,
	Rg8Snorm     = 18,
	R16Snorm     = 19,
	R8Snorm      = 20,
	Rgba32i      = 21,
	Rgba16i      = 22,
	Rgba8i       = 23,
	R32i         = 24,
	Rg32i        = 25,
	Rg16i        = 26,
	Rg8i         = 27,
	R16i         = 28,
	R8i          = 29,
	Rgba32ui     = 30,
	Rgba16ui     = 31,
	Rgba8ui      = 32,
	R32ui        = 33,
	Rgb10a2ui    = 34,
	Rg32ui       = 35,
	Rg16ui       = 36,
	Rg8ui        = 37,
	R16ui        = 38,
	R8ui         = 39,
	R64ui        = 40,
	R64i         = 41,
};

enum class ImageChannelOrder : uint32_t
{
	R            = 0,
	A            = 1,
	RG           = 2,
	RA           = 3,
	RGB          = 4,
	RGBA         = 5,
	BGRA         = 6,
	ARGB         = 7,
	Intensity    = 8,
	Luminance    = 9,
	Rx           = 10,
	RGx          = 11,
	RGBx         = 12,
	Depth        = 13,
	DepthStencil = 14,
	sRGB         = 15,
	sRGBx        = 16,
	sRGBA        = 17,
	sBGRA        = 18,
	ABGR         = 19,
};

enum class ImageChannelDataType : uint32_t
{
	SnormInt8        = 0,
	SnormInt16       = 1,
	UnormInt8        = 2,
	UnormInt16       = 3,
	UnormShort565    = 4,
	UnormShort555    = 5,
	UnormInt101010   = 6,
	SignedInt8       = 7,
	SignedInt16      = 8,
	SignedInt32      = 9,
	UnsignedInt8     = 10,
	UnsignedInt16    = 11,
	UnsignedInt32    = 12,
	HalfFloat        = 13,
	Float            = 14,
	UnormInt24       = 15,
	UnormInt101010_2 = 16,
};

enum class ImageOperands : uint32_t
{
	Bias               = 0x00001,
	Lod                = 0x00002,
	Grad               = 0x00004,
	ConstOffset        = 0x00008,
	Offset             = 0x00010,
	ConstOffsets       = 0x00020,
	Sample             = 0x00040,
	MinLod             = 0x00080,
	MakeTexelAvailable = 0x00100,
	MakeTexelVisible   = 0x00200,
	NonPrivateTexel    = 0x00400,
	VolatileTexel      = 0x00800,
	SignExtend         = 0x01000,
	ZeroExtend         = 0x02000,
	Nontemporal        = 0x04000,
	Offsets            = 0x10000,
};

enum class FpFastMathMode : uint32_t
{
	None                      = 0x0,
	NotNaN                    = 0x1,
	NotInf                    = 0x2,
	NSZ                       = 0x4,
	AllowRecip                = 0x8,
	Fast                      = 0x10,
	AllowContractFastINTEL    = 0x10000,
	AllowContractReassocINTEL = 0x20000,
};

enum class FpRoundingMode : uint32_t
{
	RTE = 0,
	RTZ = 1,
	RTP = 2,
	RTN = 3,
};

enum class LinkageType : uint32_t
{
	Export = 0,
	Import = 1,
	LinkOnceODR = 2,
};

enum class AccessQualifier : uint32_t
{
	ReadOnly = 0,
	WriteOnly = 1,
	ReadWrite = 2,
};

enum class FunctionParameterAttribute : uint32_t
{
	Zext        = 0,
	Sext        = 1,
	ByVal       = 2,
	Sret        = 3,
	NoAlias     = 4,
	NoCapture   = 5,
	NoWrite     = 6,
	NoReadWrite = 7,
};

enum class Decoration : uint32_t
{
	RelaxedPrecision                   = 0,
	SpecId                             = 1,
	Block                              = 2,
	BufferBlock                        = 3,
	RowMajor                           = 4,
	ColMajor                           = 5,
	ArrayStride                        = 6,
	MatrixStride                       = 7,
	GLSLShared                         = 8,
	GLSLPacked                         = 9,
	CPacked                            = 10,
	BuiltIn                            = 11,
	NoPerspective                      = 13,
	Flat                               = 14,
	Patch                              = 15,
	Centroid                           = 16,
	Sample                             = 17,
	Invariant                          = 18,
	Restrict                           = 19,
	Aliased                            = 20,
	Volatile                           = 21,
	Constant                           = 22,
	Coherent                           = 23,
	NonWritable                        = 24,
	NonReadable                        = 25,
	Uniform                            = 26,
	UniformId                          = 27,
	SaturatedConversion                = 28,
	Stream                             = 29,
	Location                           = 30,
	Component                          = 31,
	Index                              = 32,
	Binding                            = 33,
	DescriptorSet                      = 34,
	Offset                             = 35,
	XfbBuffer                          = 36,
	XfbStride                          = 37,
	FuncParamAttr                      = 38,
	FPRoundingMode                     = 39,
	FPFastMathMode                     = 40,
	LinkageAttributes                  = 41,
	NoContraction                      = 42,
	InputAttachmentIndex               = 43,
	Alignment                          = 44,
	MaxByteOffset                      = 45,
	AlignmentId                        = 46,
	MaxByteOffsetId                    = 47,
	NoSignedWrap                       = 4469,
	NoUnsignedWrap                     = 4470,
	ExplicitInterpAMD                  = 4999,
	OverrideCoverageNV                 = 5248,
	PassthroughNV                      = 5250,
	ViewportRelativeNV                 = 5252,
	SecondaryViewportRelativeNV        = 5256,
	PerPrimitiveNV                     = 5271,
	PerViewNV                          = 5272,
	PerTaskNV                          = 5273,
	PerVertexKHR                       = 5285,
	NonUniform                         = 5300,
	RestrictPointer                    = 5355,
	AliasedPointer                     = 5356,
	BindlessSamplerNV                  = 5398,
	BindlessImageNV                    = 5399,
	BoundSamplerNV                     = 5400,
	BoundImageNV                       = 5401,
	SIMTCallINTEL                      = 5599,
	ReferencedIndirectlyINTEL          = 5602,
	ClobberINTEL                       = 5607,
	SideEffectsINTEL                   = 5608,
	VectorComputeVariableINTEL         = 5624,
	FuncParamIOKindINTEL               = 5625,
	VectorComputeFunctionINTEL         = 5626,
	StackCallINTEL                     = 5627,
	GlobalVariableOffsetINTEL          = 5628,
	CounterBuffer                      = 5634,
	UserSemantic                       = 5635,
	UserTypeGOOGLE                     = 5636,
	FunctionRoundingModeINTEL          = 5822,
	FunctionDenormModeINTEL            = 5823,
	RegisterINTEL                      = 5825,
	MemoryINTEL                        = 5826,
	NumbanksINTEL                      = 5827,
	BankwidthINTEL                     = 5828,
	MaxPrivateCopiesINTEL              = 5829,
	SinglepumpINTEL                    = 5830,
	DoublepumpINTEL                    = 5831,
	MaxReplicatesINTEL                 = 5832,
	SimpleDualPortINTEL                = 5833,
	MergeINTEL                         = 5834,
	BankBitsINTEL                      = 5835,
	ForcePow2DepthINTEL                = 5836,
	BurstCoalesceINTEL                 = 5899,
	CacheSizeINTEL                     = 5900,
	DontStaticallyCoalesceINTEL        = 5901,
	PrefetchINTEL                      = 5902,
	StallEnableINTEL                   = 5905,
	FuseLoopsInFunctionINTEL           = 5907,
	BufferLocationINTEL                = 5921,
	IOPipeStorageINTEL                 = 5944,
	FunctionFloatingPointModeINTEL     = 6080,
	SingleElementVectorINTEL           = 6085,
	VectorComputeCallableFunctionINTEL = 6087,
	MediaBlockIOINTEL                  = 6140,
};

enum class Builtin : uint32_t
{
	Position                    = 0,
	PointSize                   = 1,
	ClipDistance                = 3,
	CullDistance                = 4,
	VertexId                    = 5,
	InstanceId                  = 6,
	PrimitiveId                 = 7,
	InvocationId                = 8,
	Layer                       = 9,
	ViewportIndex               = 10,
	TessLevelOuter              = 11,
	TessLevelInner              = 12,
	TessCoord                   = 13,
	PatchVertices               = 14,
	FragCoord                   = 15,
	PointCoord                  = 16,
	FrontFacing                 = 17,
	SampleId                    = 18,
	SamplePosition              = 19,
	SampleMask                  = 20,
	FragDepth                   = 22,
	HelperInvocation            = 23,
	NumWorkgroups               = 24,
	WorkgroupSize               = 25,
	WorkgroupId                 = 26,
	LocalInvocationId           = 27,
	GlobalInvocationId          = 28,
	LocalInvocationIndex        = 29,
	WorkDim                     = 30,
	GlobalSize                  = 31,
	EnqueuedWorkgroupSize       = 32,
	GlobalOffset                = 33,
	GlobalLinearId              = 34,
	SubgroupSize                = 36,
	SubgroupMaxSize             = 37,
	NumSubgroups                = 38,
	NumEnqueuedSubgroups        = 39,
	SubgroupId                  = 40,
	SubgroupLocalInvocationId   = 41,
	VertexIndex                 = 42,
	InstanceIndex               = 43,
	SubgroupEqMask              = 4416,
	SubgroupGeMask              = 4417,
	SubgroupGtMask              = 4418,
	SubgroupLeMask              = 4419,
	SubgroupLtMask              = 4420,
	BaseVertex                  = 4424,
	BaseInstance                = 4425,
	DrawIndex                   = 4426,
	PrimitiveShadingRateKHR     = 4432,
	DeviceIndex                 = 4438,
	ViewIndex                   = 4440,
	ShadingRateKHR              = 4444,
	BaryCoordNoPerspAMD         = 4992,
	BaryCoordNoPerspCentroidAMD = 4993,
	BaryCoordNoPerspSampleAMD   = 4994,
	BaryCoordSmoothAMD          = 4995,
	BaryCoordSmoothCentroidAMD  = 4996,
	BaryCoordSmoothSampleAMD    = 4997,
	BaryCoordPullModelAMD       = 4998,
	FragStencilRefEXT           = 5014,
	ViewportMaskNV              = 5253,
	SecondaryPositionNV         = 5257,
	SecondaryViewportMaskNV     = 5258,
	PositionPerViewNV           = 5261,
	ViewportMaskPerViewNV       = 5262,
	FullyCoveredEXT             = 5264,
	TaskCountNV                 = 5274,
	PrimitiveCountNV            = 5275,
	PrimitiveIndicesNV          = 5276,
	ClipDistancePerViewNV       = 5277,
	CullDistancePerViewNV       = 5278,
	LayerPerViewNV              = 5279,
	MeshViewCountNV             = 5280,
	MeshViewIndicesNV           = 5281,
	BaryCoordKHR                = 5286,
	BaryCoordNoPerspKHR         = 5287,
	FragSizeEXT                 = 5292,
	FragInvocationCountEXT      = 5293,
	LaunchIdKHR                 = 5319,
	LaunchSizeKHR               = 5320,
	WorldRayOriginKHR           = 5321,
	WorldRayDirectionKHR        = 5322,
	ObjectRayOriginKHR          = 5323,
	ObjectRayDirectionKHR       = 5324,
	RayTminKHR                  = 5325,
	RayTmaxKHR                  = 5326,
	InstanceCustomIndexKHR      = 5327,
	ObjectToWorldKHR            = 5330,
	WorldToObjectKHR            = 5331,
	HitTNV                      = 5332,
	HitKindKHR                  = 5333,
	CurrentRayTimeNV            = 5334,
	IncomingRayFlagsKHR         = 5351,
	RayGeometryIndexKHR         = 5352,
	WarpsPerSMNV                = 5374,
	SMCountNV                   = 5375,
	WarpIDNV                    = 5376,
	SMIDNV                      = 5377,
};

enum class SelectionControl : uint32_t
{
	None        = 0x0,
	Flatten     = 0x1,
	DontFlatten = 0x2,
};

enum class LoopControl : uint32_t
{
	None                      = 0x000000,
	Unroll                    = 0x000001,
	DontUnroll                = 0x000002,
	DependencyInfinite        = 0x000004,
	DependencyLength          = 0x000008,
	MinInterations            = 0x000010,
	MaxIterations             = 0x000020,
	IterationMultiple         = 0x000040,
	PeelCount                 = 0x000080,
	PartialCount              = 0x000100,
	InitiationIntervalINTEL   = 0x010000,
	MaxConcurrencyINTEL       = 0x020000,
	DependencyArrayINTEL      = 0x040000,
	PipelineEnableINTEL       = 0x080000,
	LoopCoalesceINTEL         = 0x100000,
	MaxInterleavingINTEL      = 0x200000,
	SpeculatedIterationsINTEL = 0x400000,
	NoFusionINTEL             = 0x800000,
};

enum class FunctionControl : uint32_t
{
	None         = 0x00000,
	Inline       = 0x00001,
	DontInline   = 0x00002,
	Pure         = 0x00004,
	Const        = 0x00008,
	OptNoneINTEL = 0x10000,
};

enum class MemorySemantics : uint32_t
{
	Relaxed                = 0x0000,
	Acquire                = 0x0002,
	Release                = 0x0004,
	AcquireRelease         = 0x0008,
	SequentiallyConsistent = 0x0010,
	UniformMemory          = 0x0040,
	SubgroupMemory         = 0x0080,
	WorkgroupMemory        = 0x0100,
	CrossWorkgroupMemory   = 0x0200,
	AtomicCounterMemory    = 0x0400,
	ImageMemory            = 0x0800,
	OutputMemory           = 0x1000,
	MakeAvailable          = 0x2000,
	MakeVisible            = 0x4000,
	Volatile               = 0x8000,
};

enum class MemoryOperands : uint32_t
{
	None                 = 0x00,
	Volatile             = 0x01,
	Aligned              = 0x02,
	Nontemporal          = 0x04,
	MakePointerAvailable = 0x08,
	MakePointerVisible   = 0x10,
	NonPrivatePointer    = 0x20,
};

enum class Scope : uint32_t
{
	CrossDevice   = 0,
	Device        = 1,
	Workgroup     = 2,
	Subgroup      = 3,
	Invocation    = 4,
	QueueFanily   = 5,
	ShaderCallKHR = 6,
};

enum class GroupOperation : uint32_t
{
	Reduce                     = 0,
	InclusiveScan              = 1,
	ExclusiveScan              = 2,
	ClusteredReduce            = 3,
	PartitionedReduceNV        = 6,
	PartitionedInclusiveScanNV = 7,
	PartitionedExclusiveScanNV = 8,
};

enum class KernelEnqueueFlags : uint32_t
{
	NoWait        = 0,
	WaitKernel    = 1,
	WaitWorkGroup = 2,
};

enum class KernelProfilingInfo : uint32_t
{
	CmdExecTime = 0x1,
};

enum class Capability : uint32_t
{
	Matrix                                      = 0,
	Shader                                      = 1,
	Geometry                                    = 2,
	Tesselation                                 = 3,
	Addresses                                   = 4,
	Linkage                                     = 5,
	Kernel                                      = 6,
	Vector16                                    = 7,
	Float16Buffer                               = 8,
	Float16                                     = 9,
	Float64                                     = 10,
	Int64                                       = 11,
	Int64Atomics                                = 12,
	ImageBasic                                  = 13,
	ImageReadWrite                              = 14,
	ImageMipmap                                 = 15,
	Pipes                                       = 17,
	Groups                                      = 18,
	DeviceEnqueue                               = 19,
	LiteralSampler                              = 20,
	AtomicStorage                               = 21,
	Int16                                       = 22,
	TesselationPointSize                        = 23,
	GeometryPointSize                           = 24,
	ImageGatherExtended                         = 25,
	StorageImageMultisample                     = 27,
	UniformBufferArrayDynamicIndexing           = 28,
	SampledImageArrayDynamicIndexing            = 29,
	StorageBufferArrayDynamicIndexing           = 30,
	StorageImageArrayDynamicIndexing            = 31,
	ClipDistance                                = 32,
	CullDistance                                = 33,
	ImageCubeArray                              = 34,
	SampleRateShading                           = 35,
	ImageRect                                   = 36,
	SampledRect                                 = 37,
	GenericPointer                              = 38,
	Int8                                        = 39,
	InputAttachment                             = 40,
	SparseResidency                             = 41,
	MinLod                                      = 42,
	Sampled1D                                   = 43,
	Image1D                                     = 44,
	SampledCubeArray                            = 45,
	SampledBuffer                               = 46,
	ImageBuffer                                 = 47,
	ImageMSArray                                = 48,
	StorageImageExtendedFormats                 = 49,
	ImageQuery                                  = 50,
	DerivativeControl                           = 51,
	InterpolationFunction                       = 52,
	TransformFeedback                           = 53,
	GeometryStreams                             = 54,
	StorageImageReadWithoutFormat               = 55,
	StorageImageWriteWithoutFormat              = 56,
	MultiViewport                               = 57,
	SubgroupDispatch                            = 58,
	NamedBarrier                                = 59,
	PipeStorage                                 = 60,
	GroupNonUniform                             = 61,
	GroupNonUniformVote                         = 62,
	GroupNonUniformArithmetic                   = 63,
	GroupNonUniformBallot                       = 64,
	GroupNonUniformShuffle                      = 65,
	GroupNonUniformShuffleRelative              = 66,
	GroupNonUniformClustered                    = 67,
	GroupNonUniformQuad                         = 68,
	ShaderLayer                                 = 69,
	ShaderViewportIndex                         = 70,
	UniformDecoration                           = 71,
	FragmentShadingRateKHR                      = 4422,
	SubgroupBallotKHR                           = 4423,
	DrawParameters                              = 4427,
	WorkgroupMemoryExplicitLayoutKHR            = 4428,
	WorkgroupMemoryExplicitLayout8BitAccessKHR  = 4429,
	WorkgroupMemoryExplicitLayout16BitAccessKHR = 4430,
	SubgroupVoteKHR                             = 4431,
	StorageBuffer16BitAccess                    = 4433,
	UniformAndStorageBuffer16BitAcess           = 4434,
	StoragePushConstant16                       = 4435,
	StorageInputOutput16                        = 4436,
	DeviceGroup                                 = 4437,
	MultiView                                   = 4439,
	VariablePointersStorageBuffer               = 4441,
	VariablePointers                            = 4442,
	AtomicStorageOps                            = 4445,
	SampleMaskPostDepthCoverage                 = 4447,
	StorageBuffer8BitAcess                      = 4448,
	UniformAndStorageBuffer8BitAccess           = 4449,
	StoragePushConstant8                        = 4450,
	DenormPreserve                              = 4464,
	DenormFlushToZero                           = 4465,
	SignedZeroInfNanPreserve                    = 4466,
	RoundingModeRTE                             = 4467,
	RoundingModeRTZ                             = 4468,
	RayQueryProvisionalKHR                      = 4471,
	RayQueryKHR                                 = 4472,
	RayTraversalPrimitiveCullingKHR             = 4478,
	RayTracingKHR                               = 4479,
	Float16ImageAMD                             = 5008,
	ImageGatherBiasLodAMD                       = 5009,
	FragmentMaskAMD                             = 5010,
	StencilExportEXT                            = 5013,
	ImageReadWriteLodAMD                        = 5015,
	Int64ImageEXT                               = 5016,
	ShaderClockKHR                              = 5055,
	SampleMaskOverrideCoverageNV                = 5249,
	GeometryShaderPassthroughNV                 = 5251,
	ShaderViewportIndexLayerEXT                 = 5254,
	ShaderViewportMaskNV                        = 5255,
	ShaderStereoViewNV                          = 5259,
	PerViewAttributesNV                         = 5260,
	FragmentFullyCoveredEXT                     = 5265,
	MeshShadingNV                               = 5266,
	ImageFootprintNV                            = 5282,
	FragmentBarycentricKHR                      = 5284,
	ComputeDerivativeGroupQuadsNV               = 5288,
	FragmentDensityEXT                          = 5291,
	GroupNonUniformPartitionedNV                = 5297,
	ShaderNonUniform                            = 5301,
	RuntimeDescriptorArray                      = 5302,
	InputAttachmentArrayDynamicIndexing         = 5303,
	UniformTexelBufferArrayDynamicIndexing      = 5304,
	StorageTexelBufferArrayDynamicIndexing      = 5305,
	UniformBufferArrayNonUniformIndexing        = 5306,
	SampledImageArrayNonUniformIndexing         = 5307,
	StorageBufferArrayNonUniformIndexing        = 5308,
	StorageImageArrayNonUniformIndexing         = 5309,
	InputAttachmentArrayNonUniformIndexing      = 5310,
	UniformTexelBufferArrayNonUniformIndexing   = 5311,
	StorageTexelBufferArrayNonUniformIndexing   = 5312,
	RayTracingNV                                = 5340,
	RayTracingMotionBlurNV                      = 5341,
	VulkanMemoryModel                           = 5345,
	VulkanMemoryModelDeviceScope                = 5346,
	PhysicalStorageBufferAddresses              = 5347,
	ComputeDerivativeGroupLinearNV              = 5350,
	RayTracingProvisionalKHR                    = 5353,
	CooperativeMatrixNV                         = 5357,
	FragmentShaderSampleInterlockEXT            = 5363,
	FragmentShaderShadingRateInterlockEXT       = 5372,
	ShaderSMBuiltinsNV                          = 5373,
	FragmentShaderPixelInterlockEXT             = 5378,
	DemoteToHelperInvocation                    = 5379,
	BindlessTextureNV                           = 5390,
	SubgroupShuffleINTEL                        = 5568,
	SubgroupBufferBlockIOINTEL                  = 5569,
	SubgroupImageBlockIOINTEL                   = 5570,
	SubgroupImageMediaBlockIOINTEL              = 5579,
	RoundToInfinityINTEL                        = 5582,
	FloatingPointModeINTEL                      = 5583,
	IntegerFunctions2INTEL                      = 5584,
	FunctionPointersINTEL                       = 5603,
	IndirectReferencesINTEL                     = 5604,
	AsmINTEL                                    = 5606,
	AtomicFloat32MinMaxEXT                      = 5612,
	AtomicFloat64MinMaxEXT                      = 5613,
	AtomicFloat16MinMaxEXT                      = 5616,
	VectorComputeINTEL                          = 5617,
	VectorAnyINTEL                              = 5619,
	ExpectAssumeKHR                             = 5629,
	SubgroupAvcMotionEstimationINTEL            = 5696,
	SubgroupAvcMotionEstimationIntraINTEL       = 5697,
	SubgroupAvcMotionEstimationChromaINTEL      = 5698,
	VariableLengthArrayINTEL                    = 5817,
	FunctionFloatControlINTEL                   = 5821,
	FPGAMemoryAttributesINTEL                   = 5824,
	FPFastMathModeINTEL                         = 5837,
	ArbitraryPrecisionIntegersINTEL             = 5844,
	ArbitraryPrecisionFloatingPointINTEL        = 5845,
	UnstructuredLoopControlsINTEL               = 5886,
	FPGALoopControlsINTEL                       = 5888,
	KernelAttributesINTEL                       = 5892,
	FPGAKernelAttributesINTEL                   = 5897,
	FPGAMemoryAccessesINTEL                     = 5898,
	FPGAClusterAttributesINTEL                  = 5904,
	LoopFuseINTEL                               = 5906,
	FPGABufferLocationINTEL                     = 5920,
	ArbitraryPrecisionFixedPointINTEL           = 5922,
	USMStorageClassesINTEL                      = 5935,
	IOPipesINTEL                                = 5943,
	BlockingPipesINTEL                          = 5945,
	FPGARegINTEL                                = 5948,
	DotProductInputAll                          = 6016,
	DotProductInput4x8Bit                       = 6017,
	DotProductInput4x8BitPacked                 = 6018,
	DotProduct                                  = 6019,
	BitInstructions                             = 6025,
	AtomicFloat32AddEXT                         = 6033,
	AtomicFloat64AddEXT                         = 6034,
	LongConstantCompositeINTEL                  = 6089,
	OptNoneINTEL                                = 6094,
	AtomicFloat16AddEXT                         = 6095,
	DebugInfoModuleINTEL                        = 6114,
};

enum class ReservedRayFlags : uint32_t
{
	None                        = 0x000,
	OpaqueKHR                   = 0x001,
	NoOpaqueKHR                 = 0x002,
	TerminateOnFirstHitKHR      = 0x004,
	SkipClosestHitShaderKHR     = 0x008,
	CullBackFacingTrianglesKHR  = 0x010,
	CullFrontFacingTrianglesKHR = 0x020,
	CullOpaqueKHR               = 0x040,
	CullNoOpaqueKHR             = 0x080,
	SkipTrianglesKHR            = 0x100,
	SkipAABBsKHR                = 0x200,
};

enum class ReservedRayQueryIntersection : uint32_t
{
	RayQueryCandidateIntersectionKHR = 0,
	RayQueryCommittedIntersectionKHR = 1,
};

enum class ReservedRayQueryCommittedType : uint32_t
{
	RayQueryCommittedIntersectionNoneKHR      = 0,
	RayQueryCommittedIntersectionTriangleKHR  = 1,
	RayQueryCommittedIntersectionGeneratedKHR = 2,
};

enum class ReservedRayQueryCandidateType : uint32_t
{
	RayQueryCandidateIntersectionTriangleKHR = 0,
	RayQueryCandidateIntersectionAABBKHR     = 1,

};

enum class ReservedFragmentShadingRate : uint32_t
{
	None              = 0x0,
	Vertical2Pixels   = 0x1,
	Vertical4Pixels   = 0x2,
	Horizontal2Pixels = 0x4,
	Horizontal4Pixels = 0x8,
};

enum class ReservedFpDenormMode : uint32_t
{
	Preserve    = 0,
	FlushToZero = 1,
};

enum class ReservedFpOperationMode : uint32_t
{
	IEEE = 0,
	ALT  = 1,
};

enum class QuantizationMode : uint32_t
{
	TRN          = 0,
	TRN_ZERO     = 1,
	RND          = 2,
	RND_ZERO     = 3,
	RND_INF      = 4,
	RND_MIN_INF  = 5,
	RND_CONV     = 6,
	RND_CONV_ODD = 7,
};

enum class OverflowMode : uint32_t
{
	WRAP     = 0,
	SAT      = 1,
	SAT_ZERO = 2,
	SAT_SYM  = 3,
};

enum class PackedVectorFormat : uint32_t
{
	PackedVectorFormat4x8Bit = 0,
};

enum class Op : uint16_t
{
	Nop                                                              = 0,
	Undef                                                            = 1,
	SizeOf                                                           = 321,
	AssumeTrueKHR                                                    = 5630,
	ExpectKHR                                                        = 5631,
	SourceContinued                                                  = 2,
	Source                                                           = 3,
	SourceExtension                                                  = 4,
	Name                                                             = 5,
	MemberName                                                       = 6,
	String                                                           = 7,
	Line                                                             = 8,
	NoLine                                                           = 317,
	ModuleProcessed                                                  = 330,
	Decorate                                                         = 71,
	MemberDecorate                                                   = 72,
	DecorationGroup                                                  = 73,
	GroupDecorate                                                    = 74,
	GroupMemberDecorate                                              = 75,
	DecorateId                                                       = 332,
	DecorateString                                                   = 5632,
	MemberDecorateString                                             = 5633,
	Extension                                                        = 10,
	ExtInstImport                                                    = 11,
	ExtInst                                                          = 12,
	MemoryModel                                                      = 14,
	EntryPoint                                                       = 15,
	ExecutionMode                                                    = 16,
	Capability                                                       = 17,
	ExecutionModeId                                                  = 331,
	TypeVoid                                                         = 19,
	TypeBool                                                         = 20,
	TypeInt                                                          = 21,
	TypeFloat                                                        = 22,
	TypeVector                                                       = 23,
	TypeMatrix                                                       = 24,
	TypeImage                                                        = 25,
	TypeSampler                                                      = 26,
	TypeSampledImage                                                 = 27,
	TypeArray                                                        = 28,
	TypeRuntimeArray                                                 = 29,
	TypeStruct                                                       = 30,
	TypeOpaque                                                       = 31,
	TypePointer                                                      = 32,
	TypeFunction                                                     = 33,
	TypeEvent                                                        = 34,
	TypeDeviceEvent                                                  = 35,
	TypeReserveId                                                    = 36,
	TypeQueue                                                        = 37,
	TypePipe                                                         = 38,
	TypeForwardPointer                                               = 39,
	TypePipeStorage                                                  = 322,
	TypeNamedBarrier                                                 = 327,
	TypeBufferSurfaceINTEL                                           = 6086,
	TypeStructContinuedINTEL                                         = 6090,
	ConstantTrue                                                     = 41,
	ConstantFalse                                                    = 42,
	Constant                                                         = 43,
	ConstantComposite                                                = 44,
	ConstantSampler                                                  = 45,
	ConstantNull                                                     = 46,
	SpecConstantTrue                                                 = 48,
	SpecConstantFalse                                                = 49,
	SpecConstant                                                     = 50,
	SpecConstantComposite                                            = 51,
	SpecConstantOp                                                   = 52,
	ConstantCompositeContinuedINTEL                                  = 6091,
	SpecConstantCompositeContinuedINTEL                              = 6092,
	Variable                                                         = 59,
	ImageTexelPointer                                                = 60,
	Load                                                             = 61,
	Store                                                            = 62,
	CopyMemory                                                       = 63,
	CopyMemorySized                                                  = 64,
	AccessChain                                                      = 65,
	InBoundsAccessChain                                              = 66,
	PtrAccessChain                                                   = 67,
	ArrayLength                                                      = 68,
	GenericPtrMemSemantics                                           = 69,
	InBoundsPtrAccessChain                                           = 70,
	PtrEqual                                                         = 401,
	PtrNotEqual                                                      = 402,
	PtrDiff                                                          = 403,
	Function                                                         = 54,
	FunctionParameter                                                = 55,
	FunctionEnd                                                      = 56,
	FunctionCall                                                     = 57,
	SampledImage                                                     = 86,
	ImageSampleImplicitLod                                           = 87,
	ImageSampleExplicitLod                                           = 88,
	ImageSampleDrefImplicitLod                                       = 89,
	ImageSampleDrefExlicitLod                                        = 90,
	ImageSampleProjImplicitLod                                       = 91,
	ImageSampleProjExplicitLod                                       = 92,
	ImageSampleProjDrefImplicitLod                                   = 93,
	ImageSampleProjDrefExplicitLod                                   = 94,
	ImageFetch                                                       = 95,
	ImageGather                                                      = 96,
	ImageDrefGather                                                  = 97,
	ImageRead                                                        = 98,
	ImageWrite                                                       = 99,
	Image                                                            = 100,
	ImageQueryFormat                                                 = 101,
	ImageQueryOrder                                                  = 102,
	ImageQuerySizeLod                                                = 103,
	ImageQuerySize                                                   = 104,
	ImageQueryLod                                                    = 105,
	ImageQueryLevels                                                 = 106,
	ImageQuerySamples                                                = 107,
	ImageSparseSampleImplicitLod                                     = 305,
	ImageSparseSampleExplicitLod                                     = 306,
	ImageSparseSampleDrefImplicitLod                                 = 307,
	ImageSparseSampleDrefExplicitLod                                 = 308,
	ImageSparseSampleProjImplicitLod                                 = 309,
	ImageSparseSampleProjExplicitLod                                 = 310,
	ImageSparseSampleProjDrefImplicitLod                             = 311,
	ImageSparseSampleProjDrefExplicitLod                             = 312,
	ImageSparseFetch                                                 = 313,
	ImageSparseGather                                                = 314,
	ImageSparseDrefGather                                            = 315,
	ImageSparseTexelsResident                                        = 316,
	ImageSparseRead                                                  = 320,
	ImageSampleFootprintNV                                           = 5283,
	ConvertFToU                                                      = 109,
	ConvertFToS                                                      = 110,
	ConvertSToF                                                      = 111,
	ConvertUToF                                                      = 112,
	UConvert                                                         = 113,
	SConvert                                                         = 114,
	FConvert                                                         = 115,
	QuantizeToF16                                                    = 116,
	ConvertPtrToU                                                    = 117,
	SatConvertSToU                                                   = 118,
	SatConvertUToS                                                   = 119,
	ConvertUToPtr                                                    = 120,
	PtrCastToGeneric                                                 = 121,
	GenericCastToPtr                                                 = 122,
	GenericCastToPtrExplicit                                         = 123,
	Bitcast                                                          = 124,
	VectorExtractDynamic                                             = 77,
	VectorInsertDynamic                                              = 78,
	VectorShuffle                                                    = 79,
	CompositeConstruct                                               = 80,
	CompositeExtract                                                 = 81,
	CompositeInsert                                                  = 82,
	CopyObject                                                       = 83,
	Transpose                                                        = 84,
	CopyLogical                                                      = 400,
	SNegate                                                          = 126,
	FNegate                                                          = 127,
	IAdd                                                             = 128,
	FAdd                                                             = 129,
	ISub                                                             = 130,
	FSub                                                             = 131,
	IMul                                                             = 132,
	FMul                                                             = 133,
	UDiv                                                             = 134,
	SDiv                                                             = 135,
	FDiv                                                             = 136,
	UMod                                                             = 137,
	SRem                                                             = 138,
	SMod                                                             = 139,
	FRem                                                             = 140,
	FMod                                                             = 141,
	VectorTimesScalar                                                = 142,
	MatrixTimesScalar                                                = 143,
	VectorTimesMatrix                                                = 144,
	MatrixTimesVector                                                = 145,
	MatrixTimesMatrix                                                = 146,
	OuterProduct                                                     = 147,
	Dot                                                              = 148,
	IAddCarry                                                        = 149,
	ISubBorrow                                                       = 150,
	UMulExtended                                                     = 151,
	SMulExtended                                                     = 152,
	SDot                                                             = 4450,
	UDot                                                             = 4451,
	SUDot                                                            = 4452,
	SDotAccSat                                                       = 4453,
	UDotAccSat                                                       = 4454,
	SUDotAccSat                                                      = 4455,
	ShiftRightLogical                                                = 194,
	ShiftRightArithmetic                                             = 195,
	ShiftLeftLogical                                                 = 196,
	BitwiseOr                                                        = 197,
	BitwiseXor                                                       = 198,
	BitwiseAnd                                                       = 199,
	Not                                                              = 200,
	BitFieldInsert                                                   = 201,
	BitFieldSExtract                                                 = 202,
	BitFieldUExtract                                                 = 203,
	BitReverse                                                       = 204,
	BitCount                                                         = 205,
	Any                                                              = 154,
	All                                                              = 155,
	IsNan                                                            = 156,
	IsInf                                                            = 157,
	IsFinite                                                         = 158,
	IsNormal                                                         = 159,
	SignBitSet                                                       = 160,
	LessOrGreater                                                    = 161,
	Ordered                                                          = 162,
	Unordered                                                        = 163,
	LogicalEqual                                                     = 164,
	LogicalNotEqual                                                  = 165,
	LogicalOr                                                        = 166,
	LogicalAnd                                                       = 167,
	LogicalNot                                                       = 168,
	Select                                                           = 169,
	IEqual                                                           = 170,
	INotEqual                                                        = 171,
	UGreaterThan                                                     = 172,
	SGreaterThan                                                     = 173,
	UGreaterThanEqual                                                = 174,
	SGreaterThanEqual                                                = 175,
	ULessThan                                                        = 176,
	SLessThan                                                        = 177,
	ULessThanEqual                                                   = 178,
	SLessThanEqual                                                   = 179,
	FOrdEqual                                                        = 180,
	FUnordEqual                                                      = 181,
	FOrdNotEqual                                                     = 182,
	FUnordNotEqual                                                   = 183,
	FOrdLessThan                                                     = 184,
	FUnordLessThan                                                   = 185,
	FOrdGreaterThan                                                  = 186,
	FUnordGreaterThan                                                = 187,
	FOrdLessThanEqual                                                = 188,
	FUnordLessThanEqual                                              = 189,
	FOrdGreaterThanEqual                                             = 190,
	FUnordGreaterThanEqual                                           = 191,
	DPdx                                                             = 207,
	DPdy                                                             = 208,
	Fwidth                                                           = 209,
	DPdxFine                                                         = 210,
	DPdyFine                                                         = 211,
	FwidthFine                                                       = 212,
	DPdxCoarse                                                       = 213,
	DPdyCoarse                                                       = 214,
	FwidthCoarse                                                     = 215,
	Phi                                                              = 245,
	LoopMerge                                                        = 246,
	SelectionMerge                                                   = 247,
	Label                                                            = 248,
	Branch                                                           = 249,
	BranchConditional                                                = 250,
	Switch                                                           = 251,
	Kill                                                             = 252,
	Return                                                           = 253,
	ReturnValue                                                      = 254,
	Unreachable                                                      = 255,
	LifetimeStart                                                    = 256,
	LifetimeStop                                                     = 257,
	TerminateInvocation                                              = 4416,
	DemoteToHelperInvocation                                         = 5380,
	AtomicLoad                                                       = 227,
	AtomicStore                                                      = 228,
	AtomicExchange                                                   = 229,
	AtomicCompareExchange                                            = 230,
	AtomicCompareExchangeWeak                                        = 231,
	AtomicIIncrement                                                 = 232,
	AtomicIDecrement                                                 = 233,
	AtomicIAdd                                                       = 234,
	AtomicISub                                                       = 235,
	AtomicSMin                                                       = 236,
	AtomicUMin                                                       = 237,
	AtomicSMax                                                       = 238,
	AtomicUMax                                                       = 239,
	AtomicAnd                                                        = 240,
	AtomicOr                                                         = 241,
	AtomicXor                                                        = 242,
	AtomicFlagTestAndSet                                             = 318,
	AtomicFlagClear                                                  = 319,
	AtomicFMinEXT                                                    = 5614,
	tomicFMaxEXT                                                     = 5615,
	AtomicFAddEXT                                                    = 6035,
	EmitVertex                                                       = 218,
	EndPrimitive                                                     = 219,
	EmitStreamVertex                                                 = 220,
	EndStreamPrimitive                                               = 221,
	ControlBarrier                                                   = 224,
	MemoryBarrier                                                    = 225,
	NamedBarrierInitialize                                           = 328,
	MemoryNamedBarrier                                               = 329,
	GroupAsyncCopy                                                   = 259,
	GroupWaitEvents                                                  = 260,
	GroupAll                                                         = 261,
	GroupAny                                                         = 262,
	GroupBroadcast                                                   = 263,
	GroupIAdd                                                        = 264,
	GroupFAdd                                                        = 265,
	GroupFMin                                                        = 266,
	GroupUMin                                                        = 267,
	GroupSMin                                                        = 268,
	GroupFMax                                                        = 269,
	GroupUMax                                                        = 270,
	GroupSMax                                                        = 217,
	SubgroupBallotKHR                                                = 4421,
	SubgroupFirstInvocationKHR                                       = 4422,
	SubgroupAllKHR                                                   = 4428,
	SubgroupAnyKHR                                                   = 4429,
	SubgroupAllEqualKHR                                              = 4430,
	SubgroupReadInvocationKHR                                        = 4432,
	GroupIAddNonUniformAMD                                           = 5000,
	GroupFAddNonUniformAMD                                           = 5001,
	GroupFMinNonUniformAMD                                           = 5002,
	GroupUMinNonUniformAMD                                           = 5003,
	GroupSMinNonUniformAMD                                           = 5004,
	GroupFMaxNonUniformAMD                                           = 5005,
	GroupUMaxNonUniformAMD                                           = 5006,
	GroupSMaxNonUniformAMD                                           = 5007,
	SubgroupShuffleINTEL                                             = 5571,
	SubgroupShuffleDownINTEL                                         = 5572,
	SubgroupShuffleUpINTEL                                           = 5573,
	SubgroupShuffleXorINTEL                                          = 5574,
	SubgroupBlockReadINTEL                                           = 5575,
	SubgroupBlockWriteINTEL                                          = 5576,
	SubgroupImageBlockReadINTEL                                      = 5577,
	SubgroupImageBlockWriteINTEL                                     = 5578,
	SubgroupImageMediaBlockReadINTEL                                 = 5580,
	SubgroupImageMediaBlockWriteINTEL                                = 5581,
	EnqueueMarker                                                    = 291,
	EnqueueKernel                                                    = 292,
	GetKernelNDrangeSubGroupCount                                    = 293,
	GetKernelNDrangeMaxSubGroupSize                                  = 294,
	GetKernelWorkGroupSize                                           = 295,
	GetKernelPreferredWorkGroupSizeMultiple                          = 296,
	RetainEvent                                                      = 297,
	ReleaseEvent                                                     = 298,
	CreateUserEvent                                                  = 299,
	IsValidEvent                                                     = 300,
	SetUserEventStatus                                               = 301,
	CaptureEventProfilingInfo                                        = 302,
	GetDefaultQueue                                                  = 303,
	BuildNDRange                                                     = 304,
	GetKernelLocalSizeForSubgroupCount                               = 325,
	GetKernelMaxNumSubgroups                                         = 326,
	ReadPipe                                                         = 274,
	WritePipe                                                        = 275,
	ReservedReadPipe                                                 = 276,
	ReservedWritePipe                                                = 277,
	ReserveReadPipePackets                                           = 278,
	ReserveWritePipePackets                                          = 279,
	CommitReadPipe                                                   = 280,
	CommitWritePipe                                                  = 281,
	IsValidReserveId                                                 = 282,
	GetNumPipePackets                                                = 283,
	GetMaxPipePackets                                                = 284,
	GroupReserveReadPipePackets                                      = 285,
	GroupReserveWritePipePackets                                     = 286,
	GroupCommitReadPipe                                              = 287,
	GroupCommitWritePipe                                             = 288,
	ConstantPipeStorage                                              = 323,
	CreatePipeFromPipeStorage                                        = 324,
	ReadPipeBlockingINTEL                                            = 5946,
	WritePipeBlockingINTEL                                           = 5947,
	GroupNonUniformElect                                             = 333,
	GroupNonUniformAll                                               = 334,
	GroupNonUniformAny                                               = 335,
	GroupNonUniformAllEqual                                          = 336,
	GroupNonUniformBroadcast                                         = 337,
	GroupNonUniformBroadcastFirst                                    = 338,
	GroupNonUniformBallot                                            = 339,
	GroupNonUniformInverseBallot                                     = 340,
	GroupNonUniformBallotBitExtract                                  = 341,
	GroupNonUniformBallotBitCount                                    = 342,
	GroupNonUniformBallotFindLSB                                     = 343,
	GroupNonUniformBallotFindMSB                                     = 344,
	GroupNonUniformShuffle                                           = 345,
	GroupNonUniformShuffleXor                                        = 346,
	GroupNonUniformShuffleUp                                         = 347,
	GroupNonUniformShuffleDown                                       = 348,
	GroupNonUniformIAdd                                              = 349,
	GroupNonUniformFAdd                                              = 350,
	GroupNonUniformIMul                                              = 351,
	GroupNonUniformFMul                                              = 352,
	GroupNonUniformSMin                                              = 353,
	GroupNonUniformUMin                                              = 354,
	GroupNonUniformFMin                                              = 355,
	GroupNonUniformSMax                                              = 356,
	GroupNonUniformUMax                                              = 357,
	GroupNonUniformFMax                                              = 358,
	GroupNonUniformBitwiseAnd                                        = 359,
	GroupNonUniformBitwiseOr                                         = 360,
	GroupNonUniformBitwiseXor                                        = 361,
	GroupNonUniformLogicalAnd                                        = 362,
	GroupNonUniformLogicalOr                                         = 363,
	GroupNonUniformLogicalXor                                        = 364,
	GroupNonUniformQuadBroadcast                                     = 365,
	GroupNonUniformQuadSwap                                          = 366,
	GroupNonUniformPartitionNV                                       = 5296,

	// Reserved

	TraceRayKHR                                                      = 4445,
	ExecuteCallableKHR                                               = 4446,
	ConvertUToAccelerationStructureKHR                               = 4447,
	IgnoreIntersectionKHR                                            = 4448,
	TerminateRayKHR                                                  = 4449,
	TypeRayQueryKHR                                                  = 4472,
	RayQueryInitializeKHR                                            = 4473,
	RayQueryTerminateKHR                                             = 4474,
	RayQueryGenerateIntersectionKHR                                  = 4475,
	RayQueryConfirmIntersectionKHR                                   = 4476,
	RayQueryProceedKHR                                               = 4477,
	RayQueryGetIntersectionTypeKHR                                   = 4479,
	FragmentMaskFetchAMD                                             = 5011,
	FragmentFetchAMD                                                 = 5012,
	ReadClockKHR                                                     = 5056,
	WritePackedPrimitiveIndices4x8NV                                 = 5299,
	ReportIntersectionNV                                             = 5334,
	IgnoreIntersectionNV                                             = 5335,
	TerminateRayNV                                                   = 5336,
	TraceNV                                                          = 5337,
	TraceMotionNV                                                    = 5338,
	TraceRayMotionNV                                                 = 5339,
	TypeAccelerationStructureNV                                      = 5341,
	ExecuteCallableNV                                                = 5344,
	TypeCooperativeMatrixNV                                          = 5358,
	CooperativeMatrixLoadNV                                          = 5359,
	CooperativeMatrixStoreNV                                         = 5360,
	CooperativeMatrixMulAddNV                                        = 5361,
	CooperativeMatrixLengthNV                                        = 5362,
	BeginInvocationInterlockEXT                                      = 5364,
	EndInvocationInterlockEXT                                        = 5365,
	IsHelperInvocationEXT                                            = 5381,
	ConvertUToImageNV                                                = 5391,
	ConvertUToSamplerNV                                              = 5392,
	ConvertImageToUNV                                                = 5393,
	ConvertSamplerToUNV                                              = 5394,
	ConvertUToSampledImageNV                                         = 5395,
	ConvertSampledImageToUNV                                         = 5396,
	SamplerImageAddressingModeNV                                     = 5397,
	UCountLeadingZerosINTEL                                          = 5585,
	UCountTrailingZerosINTEL                                         = 5586,
	AbsISubINTEL                                                     = 5587,
	AbsUSubINTEL                                                     = 5588,
	IAddSatINTEL                                                     = 5589,
	UAddSatINTEL                                                     = 5590,
	IAverageINTEL                                                    = 5591,
	UAverageINTEL                                                    = 5592,
	IAverageRoundedINTEL                                             = 5593,
	UAverageRoundedINTEL                                             = 5594,
	ISubSatINTEL                                                     = 5595,
	USubSatINTEL                                                     = 5596,
	IMul32x16INTEL                                                   = 5597,
	UMul32x16INTEL                                                   = 5598,
	LoopControlINTEL                                                 = 5887,
	FPGARegINTEL                                                     = 5949,
	RayQueryGetRayTMinKHR                                            = 6016,
	RayQueryGetRayFlagsKHR                                           = 6017,
	RayQueryGetIntersectionTKHR                                      = 6018,
	RayQueryGetIntersectionInstanceCustomIndexKHR                    = 6019,
	RayQueryGetIntersectionInstanceIdKHR                             = 6020,
	RayQueryGetIntersectionInstanceShaderBindingTableRecordOffsetKHR = 6021,
	RayQueryGetIntersectionGeometryIndexKHR                          = 6022,
	RayQueryGetIntersectionPrimitiveIndexKHR                         = 6023,
	RayQueryGetIntersectionBarycentricsKHR                           = 6024,
	RayQueryGetIntersectionFrontFaceKHR                              = 6025,
	RayQueryGetIntersectionCandidateAABBOpaqueKHR                    = 6026,
	RayQueryGetIntersectionObjectRayDirectionKHR                     = 6027,
	RayQueryGetIntersectionObjectRayOriginKHR                        = 6028,
	RayQueryGetWorldRayDirectionKHR                                  = 6029,
	RayQueryGetWorldRayOriginKHR                                     = 6030,
	RayQueryGetIntersectionObjectToWorldKHR                          = 6031,
	RayQueryGetIntersectionWorldToObjectKHR                          = 6032,
};

#endif // SPV_DEFS_HPP_INCLUDE_GUARD
